// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLHtSN4T_yjCBoqjU0dKPojyxaUT3gNBo',
    appId: '1:593088466323:web:2eddc67059fc12c768ec66',
    messagingSenderId: '593088466323',
    projectId: 'tubesiot-3d0de',
    authDomain: 'tubesiot-3d0de.firebaseapp.com',
    databaseURL: 'https://tubesiot-3d0de-default-rtdb.firebaseio.com',
    storageBucket: 'tubesiot-3d0de.firebasestorage.app',
    measurementId: 'G-KSP972VMS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVkHhj9wlpMzGDm7PzcBnboX9ikbqZj7g',
    appId: '1:593088466323:android:eba644848b6a9ac068ec66',
    messagingSenderId: '593088466323',
    projectId: 'tubesiot-3d0de',
    databaseURL: 'https://tubesiot-3d0de-default-rtdb.firebaseio.com',
    storageBucket: 'tubesiot-3d0de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9IIg9oG95NjWVRj8Qgu3nSIjZDOPR85c',
    appId: '1:593088466323:ios:7a5339f87f3eb3c968ec66',
    messagingSenderId: '593088466323',
    projectId: 'tubesiot-3d0de',
    databaseURL: 'https://tubesiot-3d0de-default-rtdb.firebaseio.com',
    storageBucket: 'tubesiot-3d0de.firebasestorage.app',
    iosBundleId: 'com.example.tubes2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9IIg9oG95NjWVRj8Qgu3nSIjZDOPR85c',
    appId: '1:593088466323:ios:7a5339f87f3eb3c968ec66',
    messagingSenderId: '593088466323',
    projectId: 'tubesiot-3d0de',
    databaseURL: 'https://tubesiot-3d0de-default-rtdb.firebaseio.com',
    storageBucket: 'tubesiot-3d0de.firebasestorage.app',
    iosBundleId: 'com.example.tubes2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLHtSN4T_yjCBoqjU0dKPojyxaUT3gNBo',
    appId: '1:593088466323:web:27d95c2914d05e3668ec66',
    messagingSenderId: '593088466323',
    projectId: 'tubesiot-3d0de',
    authDomain: 'tubesiot-3d0de.firebaseapp.com',
    databaseURL: 'https://tubesiot-3d0de-default-rtdb.firebaseio.com',
    storageBucket: 'tubesiot-3d0de.firebasestorage.app',
    measurementId: 'G-73Y2Y60LES',
  );
}
